# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  pull_request:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Adjust the Node.js version to your project's requirements

      - name: Install Dependencies
        run: |
          npm install

      # - name: Check Code Format
      #   run: |
      #     npm run lint

      - name: Test Firestore
        env:
          API_KEY: ${{ secrets.API_KEY }}
          APP_ID: ${{ secrets.APP_ID }}
          AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
          MEASUREMENT_ID: ${{ secrets.MEASUREMENT_ID }}
          MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
        run: npm test
